name: CI

on:
  pull_request:
    branches: [solution]
    paths:
      - 'challenges/**'
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'
  push:
    branches: [solution]
    paths:
      - 'challenges/**'
      - '.github/**'
      - 'package.json'
      - 'yarn.lock'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: |
          yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

  os-compatibility:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: |
          yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

  node-compatibility:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test


  ts-compatibility:
    needs: build
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        typescript-version: ['~4.2.0', '~4.3.0', '~4.4.0','~4.5.0', latest, next, beta, rc]
        include:
          - typescript-version: '~4.2.0'
            experimental: false
            name: 'ts-4.2'
          - typescript-version: '~4.3.0'
            experimental: false
            name: 'ts-4.3'
          - typescript-version: '~4.4.0'
            experimental: false
            name: 'ts-4.4'
          - typescript-version: '~4.5.0'
            experimental: false
            name: 'ts-4.5'
          - typescript-version: latest
            experimental: false
            name: 'ts-stable'
          - typescript-version: beta
            experimental: false
            name: 'ts-beta'
          - typescript-version: rc
            experimental: true
            name: 'ts-rc'
          - typescript-version: next
            experimental: true
            name: 'ts-canary'


    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: |
          yarn
      - name: Installing TypeScript ${{ matrix.typescript-version }}
        run: |
          yarn add -WD typescript@${{ matrix.typescript-version}}
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test

